name: crDroid_build_kernel_15

env:
  KERNEL_SOURCE: 'https://github.com/crdroidandroid/android_kernel_xiaomi_cepheus'
  KERNEL_SOURCE_BRANCH: '15.0'
  KERNEL_DEFCONFIG: 'cepheus_defconfig'
  KERNEL_NAME: 'crDroid-cepheus'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up build environment
        run: |
          # Install necessary dependencies
          sudo apt-get update
          sudo apt-get install -y git make gcc-aarch64-linux-gnu bc bison flex libssl-dev ccache

      - name: Clone kernel source
        run: |
          git clone --depth=1 --branch=${{ env.KERNEL_SOURCE_BRANCH }} ${{ env.KERNEL_SOURCE }} kernel_source

      - name: Configure and build kernel
        run: |
          cd kernel_source
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make ${{ env.KERNEL_DEFCONFIG }}
          make -j$(nproc) O=out

      - name: Package kernel
        run: |
          cd out
          zip -r ${{ env.KERNEL_NAME }}.zip ./*

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "${{ env.KERNEL_NAME }}-$(date +'%Y%m%d%H%M%S')"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            kernel_source/out/${{ env.KERNEL_NAME }}.zip
